name: Run tests for jaseci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-jaseci:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e jac
        pip install -e jac-cloud
        pip install -e jac-splice-orc
        pip install pytest

    - name: Set environment for testing
      run: |
        echo "TEST_ENV=true" >> $GITHUB_ENV
    - name: Run tests
      run: pytest -x jac jac-cloud jac-splice-orc
